# Generated by Django 2.1.5 on 2020-07-30 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='summary1',
            field=models.TextField(default='this is cool'),
        ),
    ]
