# Generated by Django 2.1.5 on 2020-07-30 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20200730_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='summary1',
        ),
    ]
